package Visual;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.SystemColor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
/**
 *
 * @author Diego
 */
public class ingreso extends javax.swing.JFrame {
    
    private JLabel nombre, contrasena;
    private JPanel contentPane, pnlNort, pnlbotones;
    private JTextField txtnombre;
    private JPasswordField passwordField;
    private JButton btnIngresar, btnCancelar;
    private final JLabel lblLogo = new JLabel();
    private JLabel lblImagenMicro;
    private JLabel lblImagenCantante;
   
    public ingreso() {
      
        iniciarComponentes();
    }
public void iniciarComponentes(){
    
    	setExtendedState(MAXIMIZED_BOTH);
	setLocationRelativeTo(null);
	setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		
	contentPane = new JPanel(new BorderLayout());
	setContentPane(contentPane);
		
	pnlNort = new JPanel();
	pnlNort.setBackground(new Color(171, 0, 0));
		
	nombre = new JLabel();
	nombre.setForeground(new Color(255, 255, 255));
	nombre.setBounds(547, 319, 107, 84);
	nombre.setText("USUARIO:");
	nombre.setFont(new java.awt.Font("Yu Gothic UI", 1, 20));
	txtnombre = new JTextField(10);
	txtnombre.setLocation(728, 339);
	txtnombre.setSize(309, 55);
	txtnombre.setEnabled(true);
		
	contrasena = new JLabel();
	contrasena.setForeground(SystemColor.window);
	contrasena.setBounds(529, 413, 145, 84);
	contrasena.setText("CONTRASENA:");
	contrasena.setFont(new java.awt.Font("Yu Gothic UI", 1, 20));
	pnlNort.setLayout(null);
		
	lblImagenMicro = new JLabel("");
	lblImagenMicro.setIcon(new ImageIcon("/src/logoIco"));
	lblImagenMicro.setBounds(35, 59, 434, 666);
	pnlNort.add(lblImagenMicro);
		
	pnlNort.add(nombre);
	pnlNort.add(txtnombre);
	pnlNort.add(contrasena);
	contentPane.add(pnlNort);
		
	passwordField = new JPasswordField();
	passwordField.setBounds(728, 433, 309, 55);
	pnlNort.add(passwordField);
		
	lblLogo.setIcon(new ImageIcon("/src/logo.jpeg"));
	lblLogo.setBounds(439, 0, 716, 299);
	pnlNort.add(lblLogo);;
		
	pnlbotones = new JPanel();
	pnlbotones.setBackground(new Color(171, 0, 0));
	pnlbotones.setBounds(626, 507, 334, 61);
	pnlNort.add(pnlbotones);
	pnlbotones.setLayout(null);
		
	btnIngresar = new JButton("Ingresar");
	btnIngresar.setBounds(10, 5, 109, 29);
	pnlbotones.add(btnIngresar);
	btnIngresar.setFont(new Font("Yu Gothic UI", Font.BOLD, 15));
		
	btnCancelar = new JButton("Cancelar");
	btnCancelar.setBounds(208, 5, 116, 29);
	pnlbotones.add(btnCancelar);
	btnCancelar.setFont(new Font("Yu Gothic UI", Font.BOLD, 15));
		
	lblImagenCantante = new JLabel("");
	lblImagenCantante.setIcon(new ImageIcon("src//Logo.jpeg"));
	lblImagenCantante.setBounds(1099, 137, 434, 397);
	pnlNort.add(lblImagenCantante);
        setVisible(true);
}
 public void limpiarDatos() {
	passwordField.setText(null);
	txtnombre.setText(null);
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
